config/routes.rb
require'sidekiq/web'

Rails.application.routes.draw do

  mount Sidekiq::Web => '/sidekiq'
  
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks'
  }
  
  devise_scope :user do 
    root to: 'users/sessions#new'
  end

  resources :employees
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :employee, inverse_of: :addresses 
  validates :first_line, :second_line, :city, :district, :state, :type, presence: true 
  # disable STI
  self.inheritance_column = :_type_disabled
  validates :postal_code, presence: true, length: { is: 6 }
end 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :employee, inverse_of: :contacts 
  validates :contact_no, presence: true, uniqueness: true,
            length: { minimum: 10, maximum: 13 }, format: { with: /\A([0]|\+91)?\d{10}\z/ }
end 

app/models/document.rb
class Document < ApplicationRecord
  has_many :employee_document
  has_many :employees, through: :employee_document
  validates :document_name, presence: true, length: { maximum: 50 }
end 

app/models/employee.rb
class Employee < ApplicationRecord
  before_save { self.email = email.downcase
                self.name = name.titleize }
  has_many :addresses, dependent: :destroy, inverse_of: :employee
  validates_presence_of :addresses
  accepts_nested_attributes_for :addresses, allow_destroy: true
  validates_associated :addresses

  has_many :contacts, dependent: :destroy, inverse_of: :employee
  validates_presence_of :contacts 
  accepts_nested_attributes_for :contacts, allow_destroy: true
  validates_associated :contacts

  has_many :employee_documents, dependent: :destroy 
  
  has_many :documents, through: :employee_documents
  accepts_nested_attributes_for :documents, allow_destroy: true 
  
  validates :name, :dob, :experience, :department, :designation, :joining_date, presence: true
  validates :email, presence: true, uniqueness: { case_sensitive: false }, 
            format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
end 

app/models/employee_document.rb
class EmployeeDocument < ApplicationRecord
  belongs_to :employee
  belongs_to :document
  validates :document_id, uniqueness: { scope: :employee_id }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def after_sign_in_path_for(resource)
    employees_path
  end

 	def require_user
    if !user_signed_in?
      flash[:alert] = "Uh-oh, You need to Login to perform that action!!!"
      redirect_to root_path
    end
  end 

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :require_user

  def new
    @employee = Employee.new
    2.times{@employee.addresses.build}
    @employee.contacts.build  
  end
  
  def create
    @employee = Employee.new(employee_params) 
    if @employee.save
      flash[:notice] = "Employee was added successfully."
      redirect_to employees_path
    else
      render 'new'
    end
  end 

  def show
    @employee = Employee.find(params[:id])
  end 
  
  def edit
    @employee = Employee.find(params[:id])
  end
  
  def update
    @employee = Employee.find(params[:id]) 
    if @employee.update(employee_params)
      flash[:notice] = "Employee details were updated successfully."
      redirect_to employees_path
    else
      render 'edit'
    end       
  end 

  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy
    flash[:alert] = "Employee was Deleted" 
    redirect_to employees_path
  end

  def index
    @employees = Employee.all 
  end

  private

  def employee_params
    params.require(:employee).permit(:name, :email, :dob, :experience, :department, :designation,
                    :joining_date, addresses_attributes: [:id, :type, :first_line, :second_line, :landmark, 
                                                          :city, :district, :state, :postal_code],
                                  contacts_attributes: [:id, :contact_no, :_destroy], :document_ids=>[])
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
#  GET /resource/confirmation/new
  def new
    super
  end

  # POST /resource/confirmation
  def create
    super
  end

  # GET /resource/confirmation?confirmation_token=abcdef
  def show
    super
  end

  protected

  # The path used after resending confirmation instructions.
  def after_resending_confirmation_instructions_path_for(resource_name)
    super(resource_name)
  end

  # The path used after confirmation.
  def after_confirmation_path_for(resource_name, resource)
    super(resource_name, resource)
  end 
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  def new
    super
  end

  # POST /resource/password
  def create
    super
  end

  # GET /resource/password/edit?reset_password_token=abcdef
  def edit
    super
  end

  # PUT /resource/password
  def update
    super
  end

  protected

  def after_resetting_password_path_for(resource)
    super(resource)
  end

  # The path used after sending reset password instructions
  def after_sending_reset_password_instructions_path_for(resource_name)
    super(resource_name)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    flash[:alert] = 'Registrations are not open.'
    redirect_to new_user_session_path
  end

  # POST /resource
  def create
    flash[:alert] = 'Registrations are not open.'
    redirect_to new_user_session_path
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  def new
    super
  end

  # POST /resource/unlock
  def create
    super
  end

  # GET /resource/unlock?unlock_token=abcdef
  def show
    super
  end

  protected

  # The path used after sending unlock password instructions
  def after_sending_unlock_instructions_path_for(resource)
    super(resource)
  end

  # The path used after unlocking the resource
  def after_unlock_path_for(resource)
    super(resource)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/employees/_address.html.erb
<%= f.fields_for :addresses do |address| %>
  <div class="col-md-9">
    <%= address.label :type %> 
    <% if address.options.values.last == 0 %>
      <%= address.select :type, ["Permanent"], class: "my-1"%>
    <% else %>
      <%= address.select :type, ["Local"], class: "my-1"%>
    <% end %>
    <%= address.label :line_1 %>
    <%= address.text_field :first_line, class: "my-1" %>
    <%= address.label :line_2%>
    <%= address.text_field :second_line, class: "my-1" %>
    <%= address.label :landmark %>(Optional)
    <%= address.text_field :landmark, class: "my-1" %>
    <%= address.label :city, 'City/Town/Village' %>
    <%= address.text_field :city, class: "my-1" %>
    <%= address.label :district %>
    <%= address.text_field :district, class: "my-1" %>
    <%= address.label :state %>
    <%= address.text_field :state, class: "my-1" %>    
    <%= address.label :postal_code, 'Postal Code' %>
    <%= address.text_field :postal_code, class: "my-1" %>
  </div>
  <% if address.options.values.last == 0 %>
    <div class="my-2">
      <input type="checkbox", id="make_same", class="form-check-input"/>
      <label>Make Local Address same as Permanent Address</label>
    </div>
  <% end %>
<% end%>

app/views/employees/_form.html.erb
<div class="form m-4">
  <%= render partial: 'layouts/errors', locals: { obj: @employee } %> 
  <%= form_with model: @employee, local: true do |f| %>
    <%= f.label :name, 'Full Name' %>
    <%= f.text_field :name, placeholder: "Enter Employee's Name", class: "m-1" %>
    <%= f.label :email %>
    <%= f.text_field :email, placeholder: "Enter Email", class: "m-1" %>
    <br>
    <h3 class= "fw-bold mt-2" >Addresses:</h3>
    <div class="row justify-content-start">
      <%= render partial: 'address', locals: { f: f } %>
    </div>
    
    <h3 class= "fw-bold mt-2">Contacts:</h3>
    <div class="multi-field-wrapper">
      <div class="multi-fields">

        <%= f.nested_fields_for :contacts do |contact| %>
          <div class="multi-field">
            <%# binding.pry %>
            <%= contact.label :number, class: "m-1"%>
            <%= contact.text_field :contact_no, placeholder: "Enter Phone Number", class: "m-1" %>
            <%= contact.remove_nested_fields_link 'Remove', data: { confirm: 'Are you sure?' }, class: "link-danger remove-field"%>
          </div>
        <% end %>
      </div>
      <%= f.add_nested_fields_link :contacts, 'Add Contact', class: 'btn btn-secondary btn-sm mt-1 add-field' %>
    </div>

    <h3 class= "fw-bold mt-2" >Other Details:</h3>
    <%= f.label :date_of_birth, 'Date of Birth' %>
    <%= f.date_field :dob, placeholder: "Select Date", class: "m-1" %>

    <%= f.label :experience %>
    <%= f.text_field :experience, class: "m-1" %>
  
    <%= f.label :department %>
    <%= f.text_field :department, class: "m-1" %>
    <br>
    <%= f.label :designation %>
    <%= f.text_field :designation, class: "m-1" %>
    
    <%= f.label :joining_date, 'Joining Date' %>
    <%= f.date_field :joining_date, class: "m-1" %>
    <br>
    <h4 class="fw-bold mt-2" >Documents Submitted:</h4>
    <%= f.collection_check_boxes :document_ids, Document.all, :id, :document_name, class: "form-check" do |b| %>
      <%= b.check_box class: "form-check-input" %>
      <%= b.label class: "form-check-label" %>
    <% end %>
    <br>
    <div> 
      <%= f.submit class: "btn btn-primary mt-3" %>
    </div>
  <% end %>
</div>

<script type="text/javascript">

</script>

app/views/employees/_list.html.erb
<table class="table table-hover" >
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Email</th>
      <th>Date of Birth</th>
      <th>Experience</th>
      <th>Department</th>
      <th>Designation</th>
      <th>Joining Date</th>        
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee|%>
      <tr>
        <td><%= employee.id %></td>
        <td><%= link_to employee.name, employee_path(employee) %></td>
        <td><%= employee.email %></td>
        <td><%= employee.dob.to_formatted_s(:rfc822) %></td>
        <td><%= employee.experience %></td>
        <td><%= employee.department %></td>
        <td><%= employee.designation %></td>
        <td><%= employee.joining_date.to_formatted_s(:rfc822) %></td>  
        <td><%= link_to 'Edit', edit_employee_path(employee), class: "btn btn-secondary btn-sm" %></td>
        <td><%= link_to 'Delete', employee_path(employee), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-sm" %></td>       
      </tr>
    <% end %>
  </tbody>  
</table>

app/views/employees/edit.html.erb
<h2 class="text-center mt-2"><strong><u>Edit Employee Details</u></strong></h2>

<%= render 'form' %>

app/views/employees/index.html.erb
<div class="text-center mt-2">
  <h2><strong><u>Employee list</u></strong></h2>
  <% if @employees.any? %>
    <%= render 'list' %>
  <% else %>
    <h5>No Employees to show</h5>
  <% end %>
</div>
  

app/views/employees/new.html.erb
<h2 class="text-center mt-4"><Strong><u>Add Details for Employee</u></strong></h2>

<%= render 'form' %>

app/views/employees/show.html.erb
<h2 class="text-center mt-4"><%= @employee.name %>'s Profile</h2>
<div class="row justify-content-md-center mb-4">
  <div class="card border border-secondary" style="width: 30rem;">
    <%# <img src="#" class="card-img-top" alt="..."> %>
    <div class="card-body">
      <div class="mb-2">
        <h5>Email:</h5>
        <%= @employee.email %>
        <hr class="solid">
        <h5>Addresses:</h5>
        <ul>
          <% @employee.addresses.each do |f| %>
            <li>
              <%= f.type + " Address" %><br>
              <%= f.first_line %>
              <%= f.second_line %>
              <%= f.landmark %>
              <%= f.city %>
              <%= f.district %>
              <%= f.state %>
              <%= f.postal_code %>
            </li>
          <% end %>
        </ul>
        <hr class="solid">
        <h5>Contacts:</h5>
        <ul>
          <% @employee.contacts.each do |f|%>
            <li><%= f.contact_no %></li>
          <% end %>
        </ul>
        <hr class="solid">
        <h5>Date of Birth:</h5>
        <%= @employee.dob.to_formatted_s(:rfc822) %>
        <hr class="solid">
        <h5>Experience:</h5>
        <%= @employee.experience %>
        <hr class="solid">
        <h5>Department:</h5>
        <%= @employee.department %>
        <hr class="solid">
        <h5>Designation:</h5>
        <%= @employee.designation %>
        <hr class="solid">
        <h5>Joining Date:</h5>
        <%= @employee.joining_date.to_formatted_s(:rfc822) %>
      </div>
      <%= link_to 'Edit Profile', edit_employee_path(@employee), class: "btn btn-secondary" %>
      <%= link_to 'Back to Employee List', employees_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>  
<% end %>

app/views/layouts/_links.html.erb
<% if user_signed_in? && params[:action]=='index' %>
  <%= link_to 'Add Employee', new_employee_path, class: "btn btn-success" %>
  <%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
<% end %>

<% if user_signed_in? && (params[:action]=='new' || params[:action]=='edit') %>
  <%= link_to 'Employee List', employees_path, class: "btn btn-primary" %>
  <%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == "notice" ? "primary" : "danger" %> alert-dismissible fade show" role="alert">
    <%= msg %> 
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button> 
  </div>  
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EMSCodenote</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <div class="container mt-4 rounded">
      <%= render 'layouts/messages' %>
      <h1 class="mt-4 text-center">EMS(Employee Management System)</h1>
      <%= render 'layouts/links' %>
      <%= yield %>   
    </div>
  </body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>


<%# Commented it out to disable link to sign up from login page  %>
<%#- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%#= link_to "Sign up", new_registration_path(resource_name) %>
<%# end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%-  if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>